<a href="https://colab.research.google.com/github/Thiago383/Analise_de_Dados_com_Python/blob/main/Analis%C3%A9_de_Dados.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Ínicio

* Importando biblioteca Pandas;
* Importando uma base de dados pelo Googlo Colab;

In [ ]:
import pandas as pd

In [ ]:
# "read_excel" -> Lê o conteúdo da planilha "houses_rent.xlsx"
# aluguel_casas -> Recebe o conteúdo da planilha "houses_rent.xlsx"

aluguel_casas = pd.read_excel("/content/houses_rent.xlsx")

# Pré-processamento de Dados

* Padronização de cabeçalhos: renomeação e remoção de espaços em branco;

* Análise e inspeção: de tipos de dados das colunas;

* Conversão de tipos de dados: ajuste de colunas numéricas para int ou float.

In [ ]:
# "head()" -> moastra as 5 primeiras linhas do DataFrame.
aluguel_casas.head()

,index,city,area,rooms,bathroom,parking_spaces,floor,animal,furniture,hoa,rent_amount,property_tax,fire_insurance,total
0,0,Barcelona,240,3,3,4,-,accept,furnished,600,8000.0,1000.0,121.0,9121.0
1,1,Porto,64,2,1,1,10,accept,not furnished,540,820.0,122.0,11.0,1493.0
2,2,Barcelona,443,5,5,4,3,accept,furnished,4172,7000.0,1417.0,89.0,12680.0
3,3,Barcelona,73,2,2,1,12,accept,not furnished,700,1250.0,150.0,16.0,2116.0
4,4,Barcelona,19,1,1,0,-,not accept,not furnished,0,1200.0,41.0,16.0,1257.0

In [ ]:
# "tail()" -> mostra as 5 últimas linhas do DataFrame.
aluguel_casas.tail()

In [ ]:
# "rename(columns = {})" -> Renomea o cabeçalho, removendo os espaços em branco.
#  "aluguel_casas" -> Recebe a modificação do cabeçalho.
aluguel_casas = aluguel_casas.rename(columns = {"parking spaces": "parking_spaces", "rent amount": "rent_amount", "property tax": "property_tax", "fire insurance": "fire_insurance"})

,index,city,area,rooms,bathroom,parking_spaces,floor,animal,furniture,hoa,rent_amount,property_tax,fire_insurance,total
0,0,Barcelona,240,3,3,4,-,accept,furnished,600,8000,1000,121,9121
1,1,Porto,64,2,1,1,10,accept,not furnished,540,820,122,11,1493
2,2,Barcelona,443,5,5,4,3,accept,furnished,4172,7000,1417,89,12680
3,3,Barcelona,73,2,2,1,12,accept,not furnished,700,1250,150,16,2116
4,4,Barcelona,19,1,1,0,-,not accept,not furnished,0,1200,41,16,1257

In [ ]:
# ".dtypes" -> verifica o tipo dos objeto/objetos em um dataframe
# "()" -> se utilizar no final vai apresentar um erro "'Series' object is not callable"
aluguel_casas.dtypes

index              int64
city              object
area               int64
rooms              int64
bathroom           int64
parking_spaces     int64
floor             object
animal            object
furniture         object
hoa               object
rent_amount        int64
property_tax       int64
fire_insurance     int64
total              int64
dtype: object

In [ ]:
# ".astype" -> altera o tipo de dados
aluguel_casas = aluguel_casas.astype({"rent_amount": "float", "property_tax": "float", "fire_insurance": "float", "total": "float"})

# Mostra o valor alterado
aluguel_casas.dtypes

index               int64
city               object
area                int64
rooms               int64
bathroom            int64
parking_spaces      int64
floor              object
animal             object
furniture          object
hoa                object
rent_amount       float64
property_tax      float64
fire_insurance    float64
total             float64
dtype: object

# Análise Estrutural do DataFrame

A função .info() do Pandas fornece um resumo da estrutura do DataFrame, exibindo:

* Número total de entradas e índice associado;

* Nome das colunas e quantidade de valores não nulos em cada uma;

* Tipo de dado (dtype) de cada coluna;

* Uso de memória do DataFrame.

Essa função é útil para identificar valores ausentes, verificar tipos de dados e otimizar o consumo de memória ao trabalhar com grandes conjuntos de dados.

In [ ]:
# ".info()" -> resumo do DataFrame
aluguel_casas.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6080 entries, 0 to 6079
Data columns (total 14 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   index           6080 non-null   int64
 1   city            6080 non-null   object
 2   area            6080 non-null   int64
 3   rooms           6080 non-null   int64
 4   bathroom        6080 non-null   int64
 5   parking_spaces  6080 non-null   int64
 6   floor           6080 non-null   object
 7   animal          6080 non-null   object
 8   furniture       6080 non-null   object
 9   hoa             6080 non-null   object
 10  rent_amount     6080 non-null   float64
 11  property_tax    6080 non-null   float64
 12  fire_insurance  6080 non-null   float64
 13  total           6080 non-null   float64
dtypes: float64(4), int64(5), object(5)
memory usage: 665.1+ KB

# Introdução a Estatística

A função .describe() do Pandas gera estatísticas descritivas de um DataFrame ou de uma Série. Ela fornece um resumo estatístico das colunas numéricas por padrão, mas pode ser usada também para colunas categóricas quando especificado.

Por padrão, .describe() retorna as seguintes estatísticas para colunas
numéricas (int64, float64):

* count: Número de valores não nulos
* mean: Média aritmética
* std: Desvio padrão
* min: Menor valor
* 25%: Primeiro quartil (Q1)
* 50%: Mediana (Q2)
* 75%: Terceiro quartil (Q3)
* max: Maior valor

Se aplicado a colunas categóricas (object, category), retorna:

* count: Número de valores não nulos
* unique: Número de valores únicos
* top: Valor mais frequente
* freq: Frequência do valor mais frequente

In [ ]:
# Estatística Descritiva para colunas numéricas.
# Seleciona as colunas com o padrão "DataFrame[["coluna1", "coluna2", "coluna3", ... ]]".
# ".describe()" -> Retorna as estatísticas descritivas do DataFrame.
aluguel_casas[["area", "rooms", "bathroom", "parking_spaces", "rent_amount", "property_tax", "fire_insurance", "total"]].describe()

,area,rooms,bathroom,parking_spaces,rent_amount,property_tax,fire_insurance,total
count,6080.000000,6080.000000,6080.000000,6080.000000,6080.000000,6080.000000,6080.000000,6080.000000
mean,151.143914,2.492599,2.341612,1.756250,4395.844408,490.533224,58.204276,6033.194572
std,375.559485,1.129665,1.438860,1.611909,3576.668946,6212.549484,49.313441,8751.347700
min,10.000000,1.000000,1.000000,0.000000,420.000000,0.000000,3.000000,660.000000
25%,58.000000,2.000000,1.000000,1.000000,1800.000000,34.000000,23.000000,2451.500000
50%,100.000000,3.000000,2.000000,1.000000,3111.000000,145.000000,41.000000,4128.500000
75%,200.000000,3.000000,3.000000,2.000000,5952.500000,458.000000,77.000000,8074.000000
max,24606.000000,10.000000,10.000000,12.000000,45000.000000,366300.000000,677.000000,372700.000000

In [ ]:
# Estatísticas Descritivas para colunas categóricas.
# "include =["object"] -> "Seleciona as colunas, todas, "object".
# ".describe()" -> Retorna as estatísticas descritivas do DataFrame.
aluguel_casas.describe(include=['object'])

             city floor  animal      furniture   hoa
count        6080  6080    6080           6080  6080
unique          2    37       2              2  1292
top     Barcelona     -  accept  not furnished     0
freq         5249  1555    4666           4498  1290